### ISSUE TITLE
timetable.py fatal error

### ISSUE THREAD

**Issue by bambax** [bliksemlabs/rrrr#117]
`timetable.py` fails with this error:

```
writing out agencies to string table
Traceback (most recent call last):
  File "timetable.py", line 633, in <module>
    for agency_id,agency_name,agency_url,agency_phone,agency_timezone in [db.agency(agencyId) for agencyId,idx in sorted_agencyIds]:
TypeError: 'NoneType' object is not iterable
```

and the timetable.dat file that results is not valid (multiple messages from rrrr saying "the input file does not appear to be a timetable or is of the wrong version".

(Using [gtfs file from RATP](http://data.ratp.fr/fr/les-donnees/fiche-de-jeu-de-donnees/dataset/offre-transport-de-la-ratp-format-gtfs.html?tx_icsoddatastore_pi1%5BreturnID%5D=38) (France/Paris))

**Comment by koch-t** [comment]
This happens because the RATP data is crap, there are multiple duplicate agency_id's in agency.txt triggering this line of code
https://github.com/bliksemlabs/rrrr/blob/master/gtfsdb.py#L527
I do agree that the error-message should be improved, we'll set that as a todo.
I recommend using the Paris GTFS cleaned and improved by CanalTP, available at data.navitia.io  I've sucessfully used that feed with RRRR in the past.
