### ISSUE TITLE
Validate we are timezone aware

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#24]
With the current epoch code, we must validate that both inputs (timetable.dat and request) are timezone aware, and they don't have an offset of two hours.

**Comment by koch-t** [comment]
Make everything UTC?

**Comment by abyrd** [comment]
What needs to be "timezone aware"? I would say it's more like nothing is timezone aware. I am starting to think it might be better to not use epoch times and just do date + local offset from midnight.

**Comment by koch-t** [comment]
We also need to consider DST issues, in NL the DST change is solely based
on operday. If the DST starts on 21march, busses still drive according to
CET after 3am instead of CEST. This creates the wonderful situation where
there are still nightbusses on CET and the timetable starting up on CEST.

**Comment by abyrd** [comment]
I have been mulling over this. I already mentioned the DST problem last time at Kinkrsoftware World HQ, and Stefan was of the opinion that it was not worth caring about. Handling DST is in fact possible to handle with minimal modifications to the current system, we just need to use date functions to determine the day 0,1,2 start rtimes instead of simple multiplication. The worst thing that will happen is we lose about 12 minutes of representable time at the end of the second day (because our 16 bits at four seconds gives us 72.8 hours); given good overflow checks this won't hurt anything at all. Even different service days running on different DST values should function correctly.

**Comment by koch-t** [comment]
DST is a bigger issue when transferring between servicedays. Which is a genuine possibility when transferring from a CEST nightbus to the first dayservices.

**Comment by abyrd** [comment]
What I'm planning to do would work fine even when transferring across DST change service days. rtime in router states would be continuous, with the service day "midnight" values set to noon minus 12h, accounting for daylight saving time changes.

**Comment by skinkie** [comment]
Currently the testerrrr code gets confused on the parsed date/time. (DST isn't equal to the planners non-DST)

**Comment by abyrd** [comment]
The only remaining real reason we need epoch time at all: GTFS-RT messages use it to specify validity range.

**Comment by skinkie** [comment]
tzset() might be a good way

**Comment by koch-t** [comment]
This problem is two fold:

1 Multiple feeds/ agencies with different timezones. This is a pre-processing thing, use the lowest timezone as graph-wide timezone and add the timezonedifference to the stoptimes of agencies with higher timezones.
1 Single stations that have a different timezone from the graphtimezone, this is a rendering issue and requires to store the timezone per stop.

**Comment by koch-t** [comment]
Note that OTP (afaik) doesn't support multiple GTFS's with different timezones as well.

**Comment by koch-t** [comment]
Adressed in branch tdata4
