### ISSUE TITLE
2f: implement start selection based on a tripnumber + request time

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#55]
We are looking for a way to board a certain trip without having the knowledge of the last station. We should consider the specified tripnumber "boarded".

Basically this should start with a selector that allows to select a trip based on a tripnumber, but I could also envision it is selected based on the rollingstocknumber + timestamp.

My problem is that I don't have a clue how to initialise this state.

**Comment by abyrd** [comment]
Is using trip and time OK? We can just scan through the specified trip and set the initial state at the first stoptime after the specified time.

**Comment by skinkie** [comment]
Yeah, trip and time/date would be ok. That would also help with the other enhancement.

**Comment by skinkie** [comment]
https://github.com/abyrd/rrrr/compare/onboard_departure

**Comment by skinkie** [comment]
I disagree on the expected result:

```
ITIN 1 rides 
WALK    -2  -2     2     2 00:06:00 00:06:00 +0.0 ;walk;walk;Stop 2f3;Stop 2f3
RAIL     2   0     2     1 00:06:00 00:09:00 +0.0 ;Local train 2;;Stop 2f3;Stop 2f2
WALK    -2  -2     1     1 00:09:00 00:09:00 +0.0 ;walk;walk;Stop 2f2;Stop 2f2
```

First leg indicates that walking occurs. In my huble opinion this should be something like ALIGHT, with the correct route/trip number pair (if possible). Also the arriving time of the first leg is wrong, which should 00:04. It seems that it is taken from the departure time of the second trip.

**Comment by abyrd** [comment]
The onboard depart strategy is simple: it finds the next stop you could alight at on the start trip and plans for that stop. This has to work seamlessly with all the other aspects of searches like reversal, so it's much more straightforward if you just plan from the stop in this way.

Does it really make sense to hack a bunch of special cases in just to make the results look pretty?

**Comment by skinkie** [comment]
The discussion is never about 'hacking' something. It is about solving a use-case properly.

Considering the following testcase:
Instead of taking the local train back, we extend the interncity trip with one stop. Thus it would optimally present that staying in the vehicle would be the best option. How would that be rendered?

(I extend the network with one stop to prevent the more simplistic 'alight at the next stop' case.)

**Comment by abyrd** [comment]
It would still include the walk leg, but would reboard the same trip. My point is that the walk leg is an artifact of how the problem is solved, it should be ignored, and only the rest of the plan is relevant. We could just erase it after the fact if that would look better.

There are other ways to solve this problem, for example by actually starting round 0 of the search process with only this particular trip boarded. That would require modifying things about the algorithm and other code though. I do not want to end up doing that several times correcting poor decisions.

The fundamental problem is that there is no "place" (stopid) in the working state that represents a temporary onboard location. If we had one I suppose it would need to be the highest stop index +1.

Another option would be to start at the previous stop rather than the next stop on the route and flag only the specific route you are on. This would give a more "natural" representation of the first transfer (or non-transfer as the case might be).

**Comment by abyrd** [comment]
Actually, if we don't store any state for the temporary location it can be 
(uint32_max - a_small_positive_integer). That actually makes pretty good sense and places a meaningful value in the request struct.

**Comment by abyrd** [comment]
Hmm. Actually maybe reversal makes no sense at all in the onboard depart context. With reversal out of the picture this becomes much cleaner. Thinking it through and will implement accordingly.

**Comment by skinkie** [comment]
If you are able to make the boarding location fixed you may start at the location where the train left. We do need to prevent this boarding location changes to a more optimal route, because we are riding on the edge already.

**Comment by abyrd** [comment]
Yep, we're saying the same thing.

**Comment by skinkie** [comment]
Thanks for taking care of it.
