### ISSUE TITLE
should we show legs that are less than one minute? (per transit)

### ISSUE THREAD

**Issue by skinkie** [bliksemlabs/rrrr#75]
See screenshot Bob.
![bob](https://f.cloud.github.com/assets/502394/1209160/f0a3fd76-25e2-11e3-809e-662a6e2fba4d.png)

**Comment by koch-t** [comment]
What does the itinerary above show?

**Comment by koch-t** [comment]
We shouldnt show such short legs but i rather show such a crap advice than nothing.

This also a matter of intineraries towards points instead of stops. That would enable us to do longer walks to stations where we don't have transfers.

**Comment by abyrd** [comment]
I think it's safe to drop tiny walk legs at the beginning and end of the itinerary in the UI. 

On intermediate walk legs, you could show the duration rather than exact times, but should always show the instruction to walk or wait (just "Walk to Prins Hendrikkade (1 min)" ) which might fit on one line and compact the display.

One problem is that we have many stops with similar names, so maybe we should characterize them by the type of routes that stop there. After alighting at an Amsterdam C rail platform: "walk to Amsterdam Centraal (bus stop)"

**Comment by koch-t** [comment]
@abyrd  that's not really the issue here, but i've done that in the currently unreleased version of Bliksem4Android, at least cut away all legs at the beginning and end with the same name but different (virtual) platform. 

Issue here is that tiny BUS segment at the end. That is a one stop journey where you can almost see the alighting stop at the boarding stop. Even a traveller with a free pass will probably not consider taking the bus for that segment. http://goo.gl/maps/CLmRK This would probably be a 90 eurocent journey for paid travellers..
Doing this properly would require to implement itineraries to coordinates instead of just stops where we create walk edges to nearby busstops and less nearby trainstations.

**Comment by koch-t** [comment]
And i fully agree with your remark about similar stopnames. 9292 has solved this by endlessly making up postfixes that never trickled downstream to operators creating the wonderful situation where there is a Dam Oost and a Dam West but the systems at GVB only know a "Dam" creating conflict between 9292 itineraries and onboard passenger information.
I have a small hope that the national database for bussstops solves this.

**Comment by abyrd** [comment]
RE "that tiny BUS segment at the end": That means there is probably a path with less transfers that reaches the destination in very slightly more time, or roughly the same time. It's possible that reversal is simply removing this more reasonable trip to gain a few seconds.

**Comment by koch-t** [comment]
The root cause of this (snipping to particular stoppoints) has been removed in #185 Could still occur if the fastest station lays right outside of the max_distance circle but.
